// @generated by `cargo xtask gen` from schemas/*.json — DO NOT EDIT (R-4).
// Edit the schemas and re-run `cargo xtask gen`.
// schema digest: blake3:ff41e17ed02cb108251d1852674c5226e8e49cfe76e21f198f4b4084ea66e4ca
#![allow(clippy::all)]

/// blake3 digest of the schema inputs this module was generated from.
pub const SCHEMA_DIGEST: &str = "blake3:ff41e17ed02cb108251d1852674c5226e8e49cfe76e21f198f4b4084ea66e4ca";

/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
///Discrete scannable entity a Finding is attached to (spec 2).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Discrete scannable entity a Finding is attached to (spec 2).",
///  "type": "object",
///  "required": [
///    "identifier",
///    "kind"
///  ],
///  "properties": {
///    "identifier": {
///      "description": "Stable identifier: root-relative POSIX path, image digest, purl, or normalized origin (DET-005).",
///      "type": "string"
///    },
///    "kind": {
///      "description": "What kind of entity this is.",
///      "$ref": "#/definitions/AssetKind"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Asset {
    ///Stable identifier: root-relative POSIX path, image digest, purl, or normalized origin (DET-005).
    pub identifier: ::std::string::String,
    ///What kind of entity this is.
    pub kind: AssetKind,
}
///Kind of scannable entity (spec 2: Asset).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Kind of scannable entity (spec 2: Asset).",
///  "type": "string",
///  "enum": [
///    "repo",
///    "file",
///    "image",
///    "package",
///    "endpoint"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum AssetKind {
    #[serde(rename = "repo")]
    Repo,
    #[serde(rename = "file")]
    File,
    #[serde(rename = "image")]
    Image,
    #[serde(rename = "package")]
    Package,
    #[serde(rename = "endpoint")]
    Endpoint,
}
impl ::std::fmt::Display for AssetKind {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Repo => f.write_str("repo"),
            Self::File => f.write_str("file"),
            Self::Image => f.write_str("image"),
            Self::Package => f.write_str("package"),
            Self::Endpoint => f.write_str("endpoint"),
        }
    }
}
impl ::std::str::FromStr for AssetKind {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "repo" => Ok(Self::Repo),
            "file" => Ok(Self::File),
            "image" => Ok(Self::Image),
            "package" => Ok(Self::Package),
            "endpoint" => Ok(Self::Endpoint),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for AssetKind {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for AssetKind {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for AssetKind {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///The scope block of a ScopeAuthorization (spec 9.1). exclude always beats include (SEC-002); wildcards must not span a public suffix (SEC-003).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "The scope block of a ScopeAuthorization (spec 9.1). exclude always beats include (SEC-002); wildcards must not span a public suffix (SEC-003).",
///  "type": "object",
///  "required": [
///    "attestation",
///    "authorized_by",
///    "include",
///    "permitted_methods",
///    "signature",
///    "valid_from",
///    "valid_until"
///  ],
///  "properties": {
///    "attestation": {
///      "description": "Statement that written authorization is on file; must be non-empty (A-1, enforced by multiscan-scope).",
///      "type": "string"
///    },
///    "authorized_by": {
///      "description": "Person or role granting the authorization.",
///      "type": "string"
///    },
///    "exclude": {
///      "description": "Hostname patterns explicitly out of scope; beats include (SEC-002).",
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "include": {
///      "description": "Hostname patterns in scope.",
///      "type": "array",
///      "items": {
///        "type": "string"
///      },
///      "minItems": 1
///    },
///    "permitted_methods": {
///      "description": "HTTP methods the authorization permits (PRB-003).",
///      "type": "array",
///      "items": {
///        "type": "string",
///        "enum": [
///          "GET",
///          "HEAD",
///          "OPTIONS",
///          "POST"
///        ]
///      },
///      "minItems": 1
///    },
///    "signature": {
///      "description": "ed25519 signature over the authorization content.",
///      "type": "string"
///    },
///    "valid_from": {
///      "description": "Start of validity window, RFC 3339 string; parsed and enforced by multiscan-scope (SEC-001). Kept as a string so multiscan-core stays chrono-free.",
///      "type": "string"
///    },
///    "valid_until": {
///      "description": "End of validity window, RFC 3339 string; parsed and enforced by multiscan-scope (SEC-001).",
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct AuthorizedScope {
    ///Statement that written authorization is on file; must be non-empty (A-1, enforced by multiscan-scope).
    pub attestation: ::std::string::String,
    ///Person or role granting the authorization.
    pub authorized_by: ::std::string::String,
    ///Hostname patterns explicitly out of scope; beats include (SEC-002).
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub exclude: ::std::vec::Vec<::std::string::String>,
    ///Hostname patterns in scope.
    pub include: ::std::vec::Vec<::std::string::String>,
    ///HTTP methods the authorization permits (PRB-003).
    pub permitted_methods: ::std::vec::Vec<AuthorizedScopePermittedMethodsItem>,
    ///ed25519 signature over the authorization content.
    pub signature: ::std::string::String,
    ///Start of validity window, RFC 3339 string; parsed and enforced by multiscan-scope (SEC-001). Kept as a string so multiscan-core stays chrono-free.
    pub valid_from: ::std::string::String,
    ///End of validity window, RFC 3339 string; parsed and enforced by multiscan-scope (SEC-001).
    pub valid_until: ::std::string::String,
}
///`AuthorizedScopePermittedMethodsItem`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "string",
///  "enum": [
///    "GET",
///    "HEAD",
///    "OPTIONS",
///    "POST"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum AuthorizedScopePermittedMethodsItem {
    #[serde(rename = "GET")]
    Get,
    #[serde(rename = "HEAD")]
    Head,
    #[serde(rename = "OPTIONS")]
    Options,
    #[serde(rename = "POST")]
    Post,
}
impl ::std::fmt::Display for AuthorizedScopePermittedMethodsItem {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Get => f.write_str("GET"),
            Self::Head => f.write_str("HEAD"),
            Self::Options => f.write_str("OPTIONS"),
            Self::Post => f.write_str("POST"),
        }
    }
}
impl ::std::str::FromStr for AuthorizedScopePermittedMethodsItem {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "GET" => Ok(Self::Get),
            "HEAD" => Ok(Self::Head),
            "OPTIONS" => Ok(Self::Options),
            "POST" => Ok(Self::Post),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for AuthorizedScopePermittedMethodsItem {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String>
for AuthorizedScopePermittedMethodsItem {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String>
for AuthorizedScopePermittedMethodsItem {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///Confidence in a Finding, ascending ordinal order (spec 8: Unconfirmed 0.50, Heuristic 0.70, Corroborated 0.85, Proven 1.00). Do not reorder.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Confidence in a Finding, ascending ordinal order (spec 8: Unconfirmed 0.50, Heuristic 0.70, Corroborated 0.85, Proven 1.00). Do not reorder.",
///  "type": "string",
///  "enum": [
///    "unconfirmed",
///    "heuristic",
///    "corroborated",
///    "proven"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum Confidence {
    #[serde(rename = "unconfirmed")]
    Unconfirmed,
    #[serde(rename = "heuristic")]
    Heuristic,
    #[serde(rename = "corroborated")]
    Corroborated,
    #[serde(rename = "proven")]
    Proven,
}
impl ::std::fmt::Display for Confidence {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Unconfirmed => f.write_str("unconfirmed"),
            Self::Heuristic => f.write_str("heuristic"),
            Self::Corroborated => f.write_str("corroborated"),
            Self::Proven => f.write_str("proven"),
        }
    }
}
impl ::std::str::FromStr for Confidence {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "unconfirmed" => Ok(Self::Unconfirmed),
            "heuristic" => Ok(Self::Heuristic),
            "corroborated" => Ok(Self::Corroborated),
            "proven" => Ok(Self::Proven),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for Confidence {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for Confidence {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for Confidence {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///multiscan.toml — committable, diff-friendly, no machine-specific values (CLI-007). Flags override file values; file values override defaults.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "multiscan.toml — committable, diff-friendly, no machine-specific values (CLI-007). Flags override file values; file values override defaults.",
///  "type": "object",
///  "properties": {
///    "feeds": {
///      "description": "Feed freshness and offline policy.",
///      "$ref": "#/definitions/FeedsConfig"
///    },
///    "gate": {
///      "description": "CI gate policy.",
///      "$ref": "#/definitions/GateConfig"
///    },
///    "risk": {
///      "description": "Risk scoring context.",
///      "$ref": "#/definitions/RiskConfig"
///    },
///    "rules": {
///      "description": "Pinned rule and data sources.",
///      "$ref": "#/definitions/RulesConfig"
///    },
///    "scan": {
///      "description": "Scan selection and exclusions.",
///      "$ref": "#/definitions/ScanConfig"
///    },
///    "suppress": {
///      "description": "Time-bounded, justified suppressions (CLI-006).",
///      "type": "array",
///      "items": {
///        "$ref": "#/definitions/SuppressEntry"
///      }
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Config {
    ///Feed freshness and offline policy.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub feeds: ::std::option::Option<FeedsConfig>,
    ///CI gate policy.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub gate: ::std::option::Option<GateConfig>,
    ///Risk scoring context.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub risk: ::std::option::Option<RiskConfig>,
    ///Pinned rule and data sources.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub rules: ::std::option::Option<RulesConfig>,
    ///Scan selection and exclusions.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub scan: ::std::option::Option<ScanConfig>,
    ///Time-bounded, justified suppressions (CLI-006).
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub suppress: ::std::vec::Vec<SuppressEntry>,
}
impl ::std::default::Default for Config {
    fn default() -> Self {
        Self {
            feeds: Default::default(),
            gate: Default::default(),
            risk: Default::default(),
            rules: Default::default(),
            scan: Default::default(),
            suppress: Default::default(),
        }
    }
}
///Asset criticality context for risk scoring (spec 8, factor A).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Asset criticality context for risk scoring (spec 8, factor A).",
///  "type": "string",
///  "enum": [
///    "low",
///    "medium",
///    "high",
///    "critical"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum Criticality {
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "high")]
    High,
    #[serde(rename = "critical")]
    Critical,
}
impl ::std::fmt::Display for Criticality {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Low => f.write_str("low"),
            Self::Medium => f.write_str("medium"),
            Self::High => f.write_str("high"),
            Self::Critical => f.write_str("critical"),
        }
    }
}
impl ::std::str::FromStr for Criticality {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "low" => Ok(Self::Low),
            "medium" => Ok(Self::Medium),
            "high" => Ok(Self::High),
            "critical" => Ok(Self::Critical),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for Criticality {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for Criticality {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for Criticality {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///Data classification context; sensitive/regulated adds +0.10 to factor A, clamped at 1.30 (spec 8).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Data classification context; sensitive/regulated adds +0.10 to factor A, clamped at 1.30 (spec 8).",
///  "type": "string",
///  "enum": [
///    "public",
///    "internal",
///    "sensitive",
///    "regulated"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum DataClassification {
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "internal")]
    Internal,
    #[serde(rename = "sensitive")]
    Sensitive,
    #[serde(rename = "regulated")]
    Regulated,
}
impl ::std::fmt::Display for DataClassification {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Public => f.write_str("public"),
            Self::Internal => f.write_str("internal"),
            Self::Sensitive => f.write_str("sensitive"),
            Self::Regulated => f.write_str("regulated"),
        }
    }
}
impl ::std::str::FromStr for DataClassification {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "public" => Ok(Self::Public),
            "internal" => Ok(Self::Internal),
            "sensitive" => Ok(Self::Sensitive),
            "regulated" => Ok(Self::Regulated),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for DataClassification {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for DataClassification {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for DataClassification {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///Static declaration of an Engine's identity and capabilities (spec 6.1).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Static declaration of an Engine's identity and capabilities (spec 6.1).",
///  "type": "object",
///  "required": [
///    "finding_classes",
///    "id",
///    "layers",
///    "network_impact",
///    "requires_authorization",
///    "severity_map",
///    "version"
///  ],
///  "properties": {
///    "finding_classes": {
///      "description": "Finding classes this engine can emit.",
///      "type": "array",
///      "items": {
///        "$ref": "#/definitions/FindingClass"
///      }
///    },
///    "id": {
///      "description": "Engine id, e.g. multiscan.sca.",
///      "type": "string"
///    },
///    "layers": {
///      "description": "Layers this engine participates in.",
///      "type": "array",
///      "items": {
///        "$ref": "#/definitions/Layer"
///      }
///    },
///    "network_impact": {
///      "description": "ReadOnly or ActiveSafe; no destructive variant exists (ENG-001).",
///      "$ref": "#/definitions/NetworkImpact"
///    },
///    "requires_authorization": {
///      "description": "Whether scanning requires a ScopeAuthorization (spec 9).",
///      "type": "boolean"
///    },
///    "rule_set": {
///      "description": "Rule corpus the engine executes, if any.",
///      "$ref": "#/definitions/RuleSetRef"
///    },
///    "severity_map": {
///      "description": "Explicit mapping from engine-native rule severity labels to Severity. Inferred or passthrough severity is forbidden (ENG-004).",
///      "type": "object",
///      "additionalProperties": {
///        "$ref": "#/definitions/Severity"
///      }
///    },
///    "version": {
///      "description": "Engine version.",
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct EngineManifest {
    ///Finding classes this engine can emit.
    pub finding_classes: ::std::vec::Vec<FindingClass>,
    ///Engine id, e.g. multiscan.sca.
    pub id: ::std::string::String,
    ///Layers this engine participates in.
    pub layers: ::std::vec::Vec<Layer>,
    ///ReadOnly or ActiveSafe; no destructive variant exists (ENG-001).
    pub network_impact: NetworkImpact,
    ///Whether scanning requires a ScopeAuthorization (spec 9).
    pub requires_authorization: bool,
    ///Rule corpus the engine executes, if any.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub rule_set: ::std::option::Option<RuleSetRef>,
    ///Explicit mapping from engine-native rule severity labels to Severity. Inferred or passthrough severity is forbidden (ENG-004).
    pub severity_map: std::collections::BTreeMap<::std::string::String, Severity>,
    ///Engine version.
    pub version: ::std::string::String,
}
///Non-destructive proof attached to a Finding (spec 2). Never contains secret values (SEC-101).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Non-destructive proof attached to a Finding (spec 2). Never contains secret values (SEC-101).",
///  "type": "object",
///  "required": [
///    "kind",
///    "summary"
///  ],
///  "properties": {
///    "dependency_path": {
///      "description": "For transitive dependencies: purl chain from a direct dependency to the vulnerable one (SCA-003).",
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "detail": {
///      "description": "Structured, redacted evidence payload.",
///      "type": "object"
///    },
///    "kind": {
///      "description": "Evidence kind, e.g. lockfile_entry, http_exchange, matched_resource.",
///      "type": "string"
///    },
///    "summary": {
///      "description": "Human-readable one-line summary, redaction already applied.",
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Evidence {
    ///For transitive dependencies: purl chain from a direct dependency to the vulnerable one (SCA-003).
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub dependency_path: ::std::vec::Vec<::std::string::String>,
    ///Structured, redacted evidence payload.
    #[serde(default, skip_serializing_if = "::serde_json::Map::is_empty")]
    pub detail: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
    ///Evidence kind, e.g. lockfile_entry, http_exchange, matched_resource.
    pub kind: ::std::string::String,
    ///Human-readable one-line summary, redaction already applied.
    pub summary: ::std::string::String,
}
///Gate threshold: a risk score number or a severity name (spec 4.2).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Gate threshold: a risk score number or a severity name (spec 4.2).",
///  "oneOf": [
///    {
///      "description": "Minimum risk score that fails the gate.",
///      "type": "number"
///    },
///    {
///      "description": "Minimum severity that fails the gate.",
///      "$ref": "#/definitions/Severity"
///    }
///  ]
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(untagged)]
pub enum FailOn {
    Number(f64),
    Severity(Severity),
}
impl ::std::convert::From<f64> for FailOn {
    fn from(value: f64) -> Self {
        Self::Number(value)
    }
}
impl ::std::convert::From<Severity> for FailOn {
    fn from(value: Severity) -> Self {
        Self::Severity(value)
    }
}
///[feeds] section (spec 4.5, 10).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "[feeds] section (spec 4.5, 10).",
///  "type": "object",
///  "properties": {
///    "max_age": {
///      "description": "Maximum acceptable feed age, e.g. 7d (FD-004).",
///      "type": "string"
///    },
///    "offline": {
///      "description": "Never touch the network (FR-011).",
///      "type": "boolean"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct FeedsConfig {
    ///Maximum acceptable feed age, e.g. 7d (FD-004).
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub max_age: ::std::option::Option<::std::string::String>,
    ///Never touch the network (FR-011).
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub offline: ::std::option::Option<bool>,
}
impl ::std::default::Default for FeedsConfig {
    fn default() -> Self {
        Self {
            max_age: Default::default(),
            offline: Default::default(),
        }
    }
}
///One normalized, deduplicated observation — the unit of all MultiScan output (spec 2).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "One normalized, deduplicated observation — the unit of all MultiScan output (spec 2).",
///  "type": "object",
///  "required": [
///    "asset",
///    "confidence",
///    "finding_id",
///    "identity",
///    "location",
///    "risk_score",
///    "score_explanation",
///    "severity",
///    "sources",
///    "status",
///    "title"
///  ],
///  "properties": {
///    "asset": {
///      "description": "Entity the Finding is attached to.",
///      "$ref": "#/definitions/Asset"
///    },
///    "confidence": {
///      "description": "Merged confidence; two engines reporting the same id escalate to at least corroborated (spec 7.7.5).",
///      "$ref": "#/definitions/Confidence"
///    },
///    "cwe": {
///      "description": "Associated CWE ids.",
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "description": {
///      "description": "Longer human-readable description.",
///      "type": "string"
///    },
///    "evidence": {
///      "description": "Merged redacted evidence.",
///      "type": "array",
///      "items": {
///        "$ref": "#/definitions/Evidence"
///      }
///    },
///    "finding_id": {
///      "description": "Stable identity hash (spec 7.7.1).",
///      "$ref": "#/definitions/FindingId"
///    },
///    "identity": {
///      "description": "The tuple the id was computed from.",
///      "$ref": "#/definitions/IdentityKey"
///    },
///    "location": {
///      "description": "Where it was observed.",
///      "$ref": "#/definitions/Location"
///    },
///    "remediation": {
///      "description": "Fix information.",
///      "$ref": "#/definitions/Remediation"
///    },
///    "risk_score": {
///      "description": "0.0-100.0 per the spec 8 formula.",
///      "type": "number"
///    },
///    "score_explanation": {
///      "description": "Full score provenance (RSK-005).",
///      "$ref": "#/definitions/ScoreExplanation"
///    },
///    "severity": {
///      "description": "Derived ordinal severity.",
///      "$ref": "#/definitions/Severity"
///    },
///    "sources": {
///      "description": "Every engine/bridge that reported it (BRG-001).",
///      "type": "array",
///      "items": {
///        "$ref": "#/definitions/Source"
///      },
///      "minItems": 1
///    },
///    "status": {
///      "description": "Lifecycle status.",
///      "$ref": "#/definitions/FindingStatus"
///    },
///    "title": {
///      "description": "One-line human-readable title.",
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Finding {
    ///Entity the Finding is attached to.
    pub asset: Asset,
    ///Merged confidence; two engines reporting the same id escalate to at least corroborated (spec 7.7.5).
    pub confidence: Confidence,
    ///Associated CWE ids.
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub cwe: ::std::vec::Vec<::std::string::String>,
    ///Longer human-readable description.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub description: ::std::option::Option<::std::string::String>,
    ///Merged redacted evidence.
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub evidence: ::std::vec::Vec<Evidence>,
    ///Stable identity hash (spec 7.7.1).
    pub finding_id: FindingId,
    ///The tuple the id was computed from.
    pub identity: IdentityKey,
    ///Where it was observed.
    pub location: Location,
    ///Fix information.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub remediation: ::std::option::Option<Remediation>,
    ///0.0-100.0 per the spec 8 formula.
    pub risk_score: f64,
    ///Full score provenance (RSK-005).
    pub score_explanation: ScoreExplanation,
    ///Derived ordinal severity.
    pub severity: Severity,
    ///Every engine/bridge that reported it (BRG-001).
    pub sources: ::std::vec::Vec<Source>,
    ///Lifecycle status.
    pub status: FindingStatus,
    ///One-line human-readable title.
    pub title: ::std::string::String,
}
///The class of weakness a Finding describes; selects the identity tuple shape (spec 7.7.2).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "The class of weakness a Finding describes; selects the identity tuple shape (spec 7.7.2).",
///  "type": "string",
///  "enum": [
///    "vulnerable_dependency",
///    "container_vulnerability",
///    "exposed_secret",
///    "iac_misconfiguration",
///    "web_exposure",
///    "structural_pattern"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum FindingClass {
    #[serde(rename = "vulnerable_dependency")]
    VulnerableDependency,
    #[serde(rename = "container_vulnerability")]
    ContainerVulnerability,
    #[serde(rename = "exposed_secret")]
    ExposedSecret,
    #[serde(rename = "iac_misconfiguration")]
    IacMisconfiguration,
    #[serde(rename = "web_exposure")]
    WebExposure,
    #[serde(rename = "structural_pattern")]
    StructuralPattern,
}
impl ::std::fmt::Display for FindingClass {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::VulnerableDependency => f.write_str("vulnerable_dependency"),
            Self::ContainerVulnerability => f.write_str("container_vulnerability"),
            Self::ExposedSecret => f.write_str("exposed_secret"),
            Self::IacMisconfiguration => f.write_str("iac_misconfiguration"),
            Self::WebExposure => f.write_str("web_exposure"),
            Self::StructuralPattern => f.write_str("structural_pattern"),
        }
    }
}
impl ::std::str::FromStr for FindingClass {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "vulnerable_dependency" => Ok(Self::VulnerableDependency),
            "container_vulnerability" => Ok(Self::ContainerVulnerability),
            "exposed_secret" => Ok(Self::ExposedSecret),
            "iac_misconfiguration" => Ok(Self::IacMisconfiguration),
            "web_exposure" => Ok(Self::WebExposure),
            "structural_pattern" => Ok(Self::StructuralPattern),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for FindingClass {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for FindingClass {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for FindingClass {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///blake3 of the identity tuple, truncated to 32 bytes, lowercase hex (spec 7.7.1). An identity, not a security primitive.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "blake3 of the identity tuple, truncated to 32 bytes, lowercase hex (spec 7.7.1). An identity, not a security primitive.",
///  "type": "string"
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
#[serde(transparent)]
pub struct FindingId(pub ::std::string::String);
impl ::std::ops::Deref for FindingId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<FindingId> for ::std::string::String {
    fn from(value: FindingId) -> Self {
        value.0
    }
}
impl ::std::convert::From<::std::string::String> for FindingId {
    fn from(value: ::std::string::String) -> Self {
        Self(value)
    }
}
impl ::std::str::FromStr for FindingId {
    type Err = ::std::convert::Infallible;
    fn from_str(value: &str) -> ::std::result::Result<Self, Self::Err> {
        Ok(Self(value.to_string()))
    }
}
impl ::std::fmt::Display for FindingId {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        self.0.fmt(f)
    }
}
///Lifecycle status. Only a Complete engine outcome may transition a Finding to fixed (spec 7.7.4).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Lifecycle status. Only a Complete engine outcome may transition a Finding to fixed (spec 7.7.4).",
///  "type": "string",
///  "enum": [
///    "open",
///    "fixed",
///    "suppressed"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum FindingStatus {
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "fixed")]
    Fixed,
    #[serde(rename = "suppressed")]
    Suppressed,
}
impl ::std::fmt::Display for FindingStatus {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Open => f.write_str("open"),
            Self::Fixed => f.write_str("fixed"),
            Self::Suppressed => f.write_str("suppressed"),
        }
    }
}
impl ::std::str::FromStr for FindingStatus {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "open" => Ok(Self::Open),
            "fixed" => Ok(Self::Fixed),
            "suppressed" => Ok(Self::Suppressed),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for FindingStatus {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for FindingStatus {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for FindingStatus {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///[gate] section (spec 4.5).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "[gate] section (spec 4.5).",
///  "type": "object",
///  "properties": {
///    "baseline": {
///      "description": "Relative path to a baseline Finding set for delta gating.",
///      "type": "string"
///    },
///    "fail_on": {
///      "description": "Exit 1 if any Finding meets this threshold.",
///      "$ref": "#/definitions/FailOn"
///    },
///    "ignore_unfixable": {
///      "description": "Gate only on Findings with a fix available.",
///      "type": "boolean"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct GateConfig {
    ///Relative path to a baseline Finding set for delta gating.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub baseline: ::std::option::Option<::std::string::String>,
    ///Exit 1 if any Finding meets this threshold.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub fail_on: ::std::option::Option<FailOn>,
    ///Gate only on Findings with a fix available.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub ignore_unfixable: ::std::option::Option<bool>,
}
impl ::std::default::Default for GateConfig {
    fn default() -> Self {
        Self {
            baseline: Default::default(),
            fail_on: Default::default(),
            ignore_unfixable: Default::default(),
        }
    }
}
///Class-discriminated identity tuple; blake3 of its canonical form is the finding_id (spec 7.7.2). No line numbers, timestamps, engine versions, or secret values (spec 7.7.3).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Class-discriminated identity tuple; blake3 of its canonical form is the finding_id (spec 7.7.2). No line numbers, timestamps, engine versions, or secret values (spec 7.7.3).",
///  "oneOf": [
///    {
///      "description": "Identity of a vulnerable dependency from a lockfile or manifest.",
///      "type": "object",
///      "required": [
///        "advisory_id",
///        "finding_class",
///        "manifest_path",
///        "purl"
///      ],
///      "properties": {
///        "advisory_id": {
///          "description": "Canonical advisory id (OSV id).",
///          "type": "string"
///        },
///        "finding_class": {
///          "description": "Discriminator.",
///          "type": "string",
///          "enum": [
///            "vulnerable_dependency"
///          ]
///        },
///        "manifest_path": {
///          "description": "Normalized lockfile/manifest path (DET-005).",
///          "type": "string"
///        },
///        "purl": {
///          "description": "Package URL: type, namespace, name, version.",
///          "type": "string"
///        }
///      },
///      "additionalProperties": false
///    },
///    {
///      "description": "Identity of a vulnerable package inside a container image.",
///      "type": "object",
///      "required": [
///        "advisory_id",
///        "finding_class",
///        "image_digest",
///        "purl"
///      ],
///      "properties": {
///        "advisory_id": {
///          "description": "Canonical advisory id (OSV id).",
///          "type": "string"
///        },
///        "finding_class": {
///          "description": "Discriminator.",
///          "type": "string",
///          "enum": [
///            "container_vulnerability"
///          ]
///        },
///        "image_digest": {
///          "description": "OCI image digest.",
///          "type": "string"
///        },
///        "purl": {
///          "description": "Package URL: type, namespace, name, version.",
///          "type": "string"
///        }
///      },
///      "additionalProperties": false
///    },
///    {
///      "description": "Identity of an exposed secret. Carries a truncated fingerprint, never the value (SEC-101).",
///      "type": "object",
///      "required": [
///        "finding_class",
///        "fingerprint",
///        "path",
///        "rule_id"
///      ],
///      "properties": {
///        "finding_class": {
///          "description": "Discriminator.",
///          "type": "string",
///          "enum": [
///            "exposed_secret"
///          ]
///        },
///        "fingerprint": {
///          "description": "Truncated secret fingerprint (SEC-101).",
///          "type": "string"
///        },
///        "path": {
///          "description": "Normalized path (DET-005).",
///          "type": "string"
///        },
///        "rule_id": {
///          "description": "Secrets rule id.",
///          "type": "string"
///        }
///      },
///      "additionalProperties": false
///    },
///    {
///      "description": "Identity of an IaC misconfiguration.",
///      "type": "object",
///      "required": [
///        "finding_class",
///        "path",
///        "policy_id",
///        "resource_address"
///      ],
///      "properties": {
///        "finding_class": {
///          "description": "Discriminator.",
///          "type": "string",
///          "enum": [
///            "iac_misconfiguration"
///          ]
///        },
///        "path": {
///          "description": "Normalized path (DET-005).",
///          "type": "string"
///        },
///        "policy_id": {
///          "description": "Policy id from the rule pack (IAC-001).",
///          "type": "string"
///        },
///        "resource_address": {
///          "description": "Address of the resource within the file.",
///          "type": "string"
///        }
///      },
///      "additionalProperties": false
///    },
///    {
///      "description": "Identity of a web exposure found by a probe template.",
///      "type": "object",
///      "required": [
///        "finding_class",
///        "origin",
///        "request_path",
///        "template_id"
///      ],
///      "properties": {
///        "finding_class": {
///          "description": "Discriminator.",
///          "type": "string",
///          "enum": [
///            "web_exposure"
///          ]
///        },
///        "origin": {
///          "description": "Normalized origin: scheme + host + port.",
///          "type": "string"
///        },
///        "request_path": {
///          "description": "Matched request path.",
///          "type": "string"
///        },
///        "template_id": {
///          "description": "Probe template id.",
///          "type": "string"
///        }
///      },
///      "additionalProperties": false
///    },
///    {
///      "description": "Identity of a structural (SAST) pattern match.",
///      "type": "object",
///      "required": [
///        "finding_class",
///        "path",
///        "rule_id",
///        "structural_hash"
///      ],
///      "properties": {
///        "finding_class": {
///          "description": "Discriminator.",
///          "type": "string",
///          "enum": [
///            "structural_pattern"
///          ]
///        },
///        "path": {
///          "description": "Normalized path (DET-005).",
///          "type": "string"
///        },
///        "rule_id": {
///          "description": "Structural rule id.",
///          "type": "string"
///        },
///        "structural_hash": {
///          "description": "Hash of tree-sitter node kinds plus normalized identifiers — never line numbers (spec 7.7.3).",
///          "type": "string"
///        }
///      },
///      "additionalProperties": false
///    }
///  ]
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(tag = "finding_class", deny_unknown_fields)]
pub enum IdentityKey {
    ///Identity of a vulnerable dependency from a lockfile or manifest.
    #[serde(rename = "vulnerable_dependency")]
    VulnerableDependency {
        ///Canonical advisory id (OSV id).
        advisory_id: ::std::string::String,
        ///Normalized lockfile/manifest path (DET-005).
        manifest_path: ::std::string::String,
        ///Package URL: type, namespace, name, version.
        purl: ::std::string::String,
    },
    ///Identity of a vulnerable package inside a container image.
    #[serde(rename = "container_vulnerability")]
    ContainerVulnerability {
        ///Canonical advisory id (OSV id).
        advisory_id: ::std::string::String,
        ///OCI image digest.
        image_digest: ::std::string::String,
        ///Package URL: type, namespace, name, version.
        purl: ::std::string::String,
    },
    ///Identity of an exposed secret. Carries a truncated fingerprint, never the value (SEC-101).
    #[serde(rename = "exposed_secret")]
    ExposedSecret {
        ///Truncated secret fingerprint (SEC-101).
        fingerprint: ::std::string::String,
        ///Normalized path (DET-005).
        path: ::std::string::String,
        ///Secrets rule id.
        rule_id: ::std::string::String,
    },
    ///Identity of an IaC misconfiguration.
    #[serde(rename = "iac_misconfiguration")]
    IacMisconfiguration {
        ///Normalized path (DET-005).
        path: ::std::string::String,
        ///Policy id from the rule pack (IAC-001).
        policy_id: ::std::string::String,
        ///Address of the resource within the file.
        resource_address: ::std::string::String,
    },
    ///Identity of a web exposure found by a probe template.
    #[serde(rename = "web_exposure")]
    WebExposure {
        ///Normalized origin: scheme + host + port.
        origin: ::std::string::String,
        ///Matched request path.
        request_path: ::std::string::String,
        ///Probe template id.
        template_id: ::std::string::String,
    },
    ///Identity of a structural (SAST) pattern match.
    #[serde(rename = "structural_pattern")]
    StructuralPattern {
        ///Normalized path (DET-005).
        path: ::std::string::String,
        ///Structural rule id.
        rule_id: ::std::string::String,
        ///Hash of tree-sitter node kinds plus normalized identifiers — never line numbers (spec 7.7.3).
        structural_hash: ::std::string::String,
    },
}
///A detection layer selectable via --layers (spec 4.2).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "A detection layer selectable via --layers (spec 4.2).",
///  "type": "string",
///  "enum": [
///    "sca",
///    "secrets",
///    "iac",
///    "sast",
///    "probe"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum Layer {
    #[serde(rename = "sca")]
    Sca,
    #[serde(rename = "secrets")]
    Secrets,
    #[serde(rename = "iac")]
    Iac,
    #[serde(rename = "sast")]
    Sast,
    #[serde(rename = "probe")]
    Probe,
}
impl ::std::fmt::Display for Layer {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Sca => f.write_str("sca"),
            Self::Secrets => f.write_str("secrets"),
            Self::Iac => f.write_str("iac"),
            Self::Sast => f.write_str("sast"),
            Self::Probe => f.write_str("probe"),
        }
    }
}
impl ::std::str::FromStr for Layer {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "sca" => Ok(Self::Sca),
            "secrets" => Ok(Self::Secrets),
            "iac" => Ok(Self::Iac),
            "sast" => Ok(Self::Sast),
            "probe" => Ok(Self::Probe),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for Layer {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for Layer {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for Layer {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///Per-layer overrides ([scan.<layer>] sections, ADR 0004). A layer's exclude list extends the global [scan] exclude for that layer's engines only.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Per-layer overrides ([scan.<layer>] sections, ADR 0004). A layer's exclude list extends the global [scan] exclude for that layer's engines only.",
///  "type": "object",
///  "properties": {
///    "exclude": {
///      "description": "Additional glob patterns excluded for this layer only. Matched against the root-relative POSIX path; a pattern matching a directory path prunes the walk beneath it.",
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct LayerScanConfig {
    ///Additional glob patterns excluded for this layer only. Matched against the root-relative POSIX path; a pattern matching a directory path prunes the walk beneath it.
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub exclude: ::std::vec::Vec<::std::string::String>,
}
impl ::std::default::Default for LayerScanConfig {
    fn default() -> Self {
        Self {
            exclude: Default::default(),
        }
    }
}
///Where the weakness was observed. Line numbers are display-only and never enter identity (spec 7.7.3).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Where the weakness was observed. Line numbers are display-only and never enter identity (spec 7.7.3).",
///  "type": "object",
///  "required": [
///    "path"
///  ],
///  "properties": {
///    "line": {
///      "description": "1-based line number, display-only.",
///      "type": "integer"
///    },
///    "path": {
///      "description": "Root-relative POSIX path (DET-005).",
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Location {
    ///1-based line number, display-only.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub line: ::std::option::Option<i64>,
    ///Root-relative POSIX path (DET-005).
    pub path: ::std::string::String,
}
///`MultiScan`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "title": "MultiScan"
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(transparent)]
pub struct MultiScan(pub ::serde_json::Value);
impl ::std::ops::Deref for MultiScan {
    type Target = ::serde_json::Value;
    fn deref(&self) -> &::serde_json::Value {
        &self.0
    }
}
impl ::std::convert::From<MultiScan> for ::serde_json::Value {
    fn from(value: MultiScan) -> Self {
        value.0
    }
}
impl ::std::convert::From<::serde_json::Value> for MultiScan {
    fn from(value: ::serde_json::Value) -> Self {
        Self(value)
    }
}
///Network impact of an Engine. Exactly two variants; a destructive variant MUST never be added — NG-1 is enforced by this type (ENG-001).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Network impact of an Engine. Exactly two variants; a destructive variant MUST never be added — NG-1 is enforced by this type (ENG-001).",
///  "type": "string",
///  "enum": [
///    "read_only",
///    "active_safe"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum NetworkImpact {
    #[serde(rename = "read_only")]
    ReadOnly,
    #[serde(rename = "active_safe")]
    ActiveSafe,
}
impl ::std::fmt::Display for NetworkImpact {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::ReadOnly => f.write_str("read_only"),
            Self::ActiveSafe => f.write_str("active_safe"),
        }
    }
}
impl ::std::str::FromStr for NetworkImpact {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "read_only" => Ok(Self::ReadOnly),
            "active_safe" => Ok(Self::ActiveSafe),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for NetworkImpact {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for NetworkImpact {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for NetworkImpact {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///Scan profile (spec 4.2).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Scan profile (spec 4.2).",
///  "type": "string",
///  "enum": [
///    "quick",
///    "standard",
///    "thorough"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum Profile {
    #[serde(rename = "quick")]
    Quick,
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "thorough")]
    Thorough,
}
impl ::std::fmt::Display for Profile {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Quick => f.write_str("quick"),
            Self::Standard => f.write_str("standard"),
            Self::Thorough => f.write_str("thorough"),
        }
    }
}
impl ::std::str::FromStr for Profile {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "quick" => Ok(Self::Quick),
            "standard" => Ok(Self::Standard),
            "thorough" => Ok(Self::Thorough),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for Profile {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for Profile {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for Profile {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///What an Engine emits into the FindingSink: identity plus presentation, before dedup, enrichment, and scoring (spec 6.1).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "What an Engine emits into the FindingSink: identity plus presentation, before dedup, enrichment, and scoring (spec 6.1).",
///  "type": "object",
///  "required": [
///    "asset",
///    "confidence",
///    "identity",
///    "location",
///    "severity",
///    "title"
///  ],
///  "properties": {
///    "asset": {
///      "description": "Entity the observation is attached to.",
///      "$ref": "#/definitions/Asset"
///    },
///    "confidence": {
///      "description": "Engine's confidence in the observation.",
///      "$ref": "#/definitions/Confidence"
///    },
///    "cwe": {
///      "description": "Associated CWE ids, e.g. CWE-200.",
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "description": {
///      "description": "Longer human-readable description.",
///      "type": "string"
///    },
///    "evidence": {
///      "description": "Attached redacted evidence.",
///      "type": "array",
///      "items": {
///        "$ref": "#/definitions/Evidence"
///      }
///    },
///    "identity": {
///      "description": "Class-discriminated identity tuple.",
///      "$ref": "#/definitions/IdentityKey"
///    },
///    "location": {
///      "description": "Where it was observed.",
///      "$ref": "#/definitions/Location"
///    },
///    "remediation": {
///      "description": "Fix information if the engine knows it.",
///      "$ref": "#/definitions/Remediation"
///    },
///    "rule_id": {
///      "description": "Rule/policy/advisory id for sources attribution.",
///      "type": "string"
///    },
///    "severity": {
///      "description": "Severity from the engine's explicit severity map (ENG-004).",
///      "$ref": "#/definitions/Severity"
///    },
///    "title": {
///      "description": "One-line human-readable title.",
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct RawFinding {
    ///Entity the observation is attached to.
    pub asset: Asset,
    ///Engine's confidence in the observation.
    pub confidence: Confidence,
    ///Associated CWE ids, e.g. CWE-200.
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub cwe: ::std::vec::Vec<::std::string::String>,
    ///Longer human-readable description.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub description: ::std::option::Option<::std::string::String>,
    ///Attached redacted evidence.
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub evidence: ::std::vec::Vec<Evidence>,
    ///Class-discriminated identity tuple.
    pub identity: IdentityKey,
    ///Where it was observed.
    pub location: Location,
    ///Fix information if the engine knows it.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub remediation: ::std::option::Option<Remediation>,
    ///Rule/policy/advisory id for sources attribution.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub rule_id: ::std::option::Option<::std::string::String>,
    ///Severity from the engine's explicit severity map (ENG-004).
    pub severity: Severity,
    ///One-line human-readable title.
    pub title: ::std::string::String,
}
///How to fix the Finding (SCA-004).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "How to fix the Finding (SCA-004).",
///  "type": "object",
///  "required": [
///    "fix_available"
///  ],
///  "properties": {
///    "fix_available": {
///      "description": "Whether a fix exists within the current constraint.",
///      "type": "boolean"
///    },
///    "fixed_version": {
///      "description": "Lowest non-vulnerable version satisfying the existing constraint (SCA-004).",
///      "type": "string"
///    },
///    "summary": {
///      "description": "Human-readable remediation guidance.",
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Remediation {
    ///Whether a fix exists within the current constraint.
    pub fix_available: bool,
    ///Lowest non-vulnerable version satisfying the existing constraint (SCA-004).
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub fixed_version: ::std::option::Option<::std::string::String>,
    ///Human-readable remediation guidance.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub summary: ::std::option::Option<::std::string::String>,
}
///[risk] section: scoring context (spec 4.5, 8).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "[risk] section: scoring context (spec 4.5, 8).",
///  "type": "object",
///  "properties": {
///    "asset_criticality": {
///      "description": "Factor A input.",
///      "$ref": "#/definitions/Criticality"
///    },
///    "data_classification": {
///      "description": "Factor A modifier input.",
///      "$ref": "#/definitions/DataClassification"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct RiskConfig {
    ///Factor A input.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub asset_criticality: ::std::option::Option<Criticality>,
    ///Factor A modifier input.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub data_classification: ::std::option::Option<DataClassification>,
}
impl ::std::default::Default for RiskConfig {
    fn default() -> Self {
        Self {
            asset_criticality: Default::default(),
            data_classification: Default::default(),
        }
    }
}
///Reference to a versioned, content-addressed rule corpus (spec 2, FD-006).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Reference to a versioned, content-addressed rule corpus (spec 2, FD-006).",
///  "type": "object",
///  "required": [
///    "digest",
///    "id",
///    "version"
///  ],
///  "properties": {
///    "digest": {
///      "description": "Content digest of the pack.",
///      "type": "string"
///    },
///    "id": {
///      "description": "Rule pack id, e.g. cis-bundle.",
///      "type": "string"
///    },
///    "version": {
///      "description": "Rule pack version.",
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct RuleSetRef {
    ///Content digest of the pack.
    pub digest: ::std::string::String,
    ///Rule pack id, e.g. cis-bundle.
    pub id: ::std::string::String,
    ///Rule pack version.
    pub version: ::std::string::String,
}
///[rules] section: pinned rule/data sources (spec 4.5).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "[rules] section: pinned rule/data sources (spec 4.5).",
///  "type": "object",
///  "properties": {
///    "iac_pack": {
///      "description": "Pinned IaC policy pack, e.g. cis-bundle@1.9.0.",
///      "type": "string"
///    },
///    "sca_db": {
///      "description": "Pinned advisory snapshot, e.g. osv@2026-08-05.",
///      "type": "string"
///    },
///    "secrets_pack": {
///      "description": "Pinned secrets rule pack.",
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct RulesConfig {
    ///Pinned IaC policy pack, e.g. cis-bundle@1.9.0.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub iac_pack: ::std::option::Option<::std::string::String>,
    ///Pinned advisory snapshot, e.g. osv@2026-08-05.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub sca_db: ::std::option::Option<::std::string::String>,
    ///Pinned secrets rule pack.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub secrets_pack: ::std::option::Option<::std::string::String>,
}
impl ::std::default::Default for RulesConfig {
    fn default() -> Self {
        Self {
            iac_pack: Default::default(),
            sca_db: Default::default(),
            secrets_pack: Default::default(),
        }
    }
}
///[scan] section (spec 4.5).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "[scan] section (spec 4.5).",
///  "type": "object",
///  "properties": {
///    "exclude": {
///      "description": "Glob patterns to exclude, all layers. Matched against the root-relative POSIX path; a pattern matching a directory path prunes the walk beneath it. Committable, machine-independent (CLI-007).",
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "iac": {
///      "description": "IaC-layer overrides ([scan.iac]).",
///      "$ref": "#/definitions/LayerScanConfig"
///    },
///    "layers": {
///      "description": "Layers to run; default auto-detect.",
///      "type": "array",
///      "items": {
///        "$ref": "#/definitions/Layer"
///      }
///    },
///    "profile": {
///      "description": "Scan profile; default standard.",
///      "$ref": "#/definitions/Profile"
///    },
///    "sca": {
///      "description": "SCA-layer overrides ([scan.sca]).",
///      "$ref": "#/definitions/LayerScanConfig"
///    },
///    "secrets": {
///      "description": "Secrets-layer overrides ([scan.secrets]).",
///      "$ref": "#/definitions/SecretsScanConfig"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ScanConfig {
    ///Glob patterns to exclude, all layers. Matched against the root-relative POSIX path; a pattern matching a directory path prunes the walk beneath it. Committable, machine-independent (CLI-007).
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub exclude: ::std::vec::Vec<::std::string::String>,
    ///IaC-layer overrides ([scan.iac]).
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub iac: ::std::option::Option<LayerScanConfig>,
    ///Layers to run; default auto-detect.
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub layers: ::std::vec::Vec<Layer>,
    ///Scan profile; default standard.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub profile: ::std::option::Option<Profile>,
    ///SCA-layer overrides ([scan.sca]).
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub sca: ::std::option::Option<LayerScanConfig>,
    ///Secrets-layer overrides ([scan.secrets]).
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub secrets: ::std::option::Option<SecretsScanConfig>,
}
impl ::std::default::Default for ScanConfig {
    fn default() -> Self {
        Self {
            exclude: Default::default(),
            iac: Default::default(),
            layers: Default::default(),
            profile: Default::default(),
            sca: Default::default(),
            secrets: Default::default(),
        }
    }
}
///Signed record permitting probing of named remote targets (spec 9.1). No flag, env var, or config key may bypass it (SEC-009).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Signed record permitting probing of named remote targets (spec 9.1). No flag, env var, or config key may bypass it (SEC-009).",
///  "type": "object",
///  "required": [
///    "authorization_id",
///    "scope"
///  ],
///  "properties": {
///    "authorization_id": {
///      "description": "Unique id of this authorization.",
///      "type": "string"
///    },
///    "scope": {
///      "description": "The authorized scope and validity window.",
///      "$ref": "#/definitions/AuthorizedScope"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ScopeAuthorization {
    ///Unique id of this authorization.
    pub authorization_id: ::std::string::String,
    ///The authorized scope and validity window.
    pub scope: AuthorizedScope,
}
///Full provenance of a RiskScore (RSK-002, RSK-003, RSK-005).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Full provenance of a RiskScore (RSK-002, RSK-003, RSK-005).",
///  "type": "object",
///  "required": [
///    "defaults_applied",
///    "factors",
///    "formula_version",
///    "raw_product"
///  ],
///  "properties": {
///    "defaults_applied": {
///      "description": "Names of factors that fell back to documented defaults (RSK-002).",
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "factors": {
///      "description": "The five factor values used.",
///      "$ref": "#/definitions/ScoreFactors"
///    },
///    "feed_snapshot_id": {
///      "description": "FeedSnapshot the enrichment came from; absent when scoring ran without feeds (RSK-003).",
///      "type": "string"
///    },
///    "formula_version": {
///      "description": "Version of the scoring formula (RSK-004).",
///      "type": "string"
///    },
///    "raw_product": {
///      "description": "S*E*X*C*A before scaling/clamping.",
///      "type": "number"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ScoreExplanation {
    ///Names of factors that fell back to documented defaults (RSK-002).
    pub defaults_applied: ::std::vec::Vec<::std::string::String>,
    ///The five factor values used.
    pub factors: ScoreFactors,
    ///FeedSnapshot the enrichment came from; absent when scoring ran without feeds (RSK-003).
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub feed_snapshot_id: ::std::option::Option<::std::string::String>,
    ///Version of the scoring formula (RSK-004).
    pub formula_version: ::std::string::String,
    ///S*E*X*C*A before scaling/clamping.
    pub raw_product: f64,
}
///The five factors of the risk formula (spec 8).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "The five factors of the risk formula (spec 8).",
///  "type": "object",
///  "required": [
///    "asset_criticality",
///    "confidence",
///    "exploitability",
///    "exposure",
///    "severity_base"
///  ],
///  "properties": {
///    "asset_criticality": {
///      "description": "A: 0.50-1.30.",
///      "type": "number"
///    },
///    "confidence": {
///      "description": "C: 0.50-1.00.",
///      "type": "number"
///    },
///    "exploitability": {
///      "description": "X: 0.20-1.00.",
///      "type": "number"
///    },
///    "exposure": {
///      "description": "E: 0.30-1.00.",
///      "type": "number"
///    },
///    "severity_base": {
///      "description": "S: 0.05-1.00.",
///      "type": "number"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ScoreFactors {
    ///A: 0.50-1.30.
    pub asset_criticality: f64,
    ///C: 0.50-1.00.
    pub confidence: f64,
    ///X: 0.20-1.00.
    pub exploitability: f64,
    ///E: 0.30-1.00.
    pub exposure: f64,
    ///S: 0.05-1.00.
    pub severity_base: f64,
}
///[scan.secrets] overrides (ADR 0004, ADR 0005, ADR 0006): the per-layer exclude, entropy-noise control, and git-history opt-in.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "[scan.secrets] overrides (ADR 0004, ADR 0005, ADR 0006): the per-layer exclude, entropy-noise control, and git-history opt-in.",
///  "type": "object",
///  "properties": {
///    "entropy_exclude": {
///      "description": "Globs where the high-entropy fallback is silenced; precise provider rules still run there. Extends the built-in known-noise list (lockfiles, IDE metadata, minified assets — ADR 0005).",
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "exclude": {
///      "description": "Additional glob patterns excluded for the secrets layer only. Matched against the root-relative POSIX path; a pattern matching a directory path prunes the walk beneath it.",
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "history": {
///      "description": "Also scan git-history blobs (ADR 0006): committed-then-removed secrets are still live. Opt-in; requires the git CLI; bounded by hard blob/size caps; degrades to Partial when the root is not a git repository.",
///      "type": "boolean"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct SecretsScanConfig {
    ///Globs where the high-entropy fallback is silenced; precise provider rules still run there. Extends the built-in known-noise list (lockfiles, IDE metadata, minified assets — ADR 0005).
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub entropy_exclude: ::std::vec::Vec<::std::string::String>,
    ///Additional glob patterns excluded for the secrets layer only. Matched against the root-relative POSIX path; a pattern matching a directory path prunes the walk beneath it.
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub exclude: ::std::vec::Vec<::std::string::String>,
    ///Also scan git-history blobs (ADR 0006): committed-then-removed secrets are still live. Opt-in; requires the git CLI; bounded by hard blob/size caps; degrades to Partial when the root is not a git repository.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub history: ::std::option::Option<bool>,
}
impl ::std::default::Default for SecretsScanConfig {
    fn default() -> Self {
        Self {
            entropy_exclude: Default::default(),
            exclude: Default::default(),
            history: Default::default(),
        }
    }
}
///Ordinal severity, always derived from an explicit engine severity map (ENG-004). Variant order is the ordinal order — do not reorder (spec 2).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Ordinal severity, always derived from an explicit engine severity map (ENG-004). Variant order is the ordinal order — do not reorder (spec 2).",
///  "type": "string",
///  "enum": [
///    "informational",
///    "low",
///    "medium",
///    "high",
///    "critical"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum Severity {
    #[serde(rename = "informational")]
    Informational,
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "high")]
    High,
    #[serde(rename = "critical")]
    Critical,
}
impl ::std::fmt::Display for Severity {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Informational => f.write_str("informational"),
            Self::Low => f.write_str("low"),
            Self::Medium => f.write_str("medium"),
            Self::High => f.write_str("high"),
            Self::Critical => f.write_str("critical"),
        }
    }
}
impl ::std::str::FromStr for Severity {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "informational" => Ok(Self::Informational),
            "low" => Ok(Self::Low),
            "medium" => Ok(Self::Medium),
            "high" => Ok(Self::High),
            "critical" => Ok(Self::Critical),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for Severity {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for Severity {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for Severity {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///One engine or bridge that reported this Finding (BRG-001).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "One engine or bridge that reported this Finding (BRG-001).",
///  "type": "object",
///  "required": [
///    "engine_id"
///  ],
///  "properties": {
///    "engine_id": {
///      "description": "Reporting engine, e.g. multiscan.sca, or bridge tool id.",
///      "type": "string"
///    },
///    "rule_id": {
///      "description": "Rule/policy/advisory id within that engine.",
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Source {
    ///Reporting engine, e.g. multiscan.sca, or bridge tool id.
    pub engine_id: ::std::string::String,
    ///Rule/policy/advisory id within that engine.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub rule_id: ::std::option::Option<::std::string::String>,
}
///One [[suppress]] entry. justification, approver, and expires are all mandatory — permanent suppression does not exist (CLI-006).
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "One [[suppress]] entry. justification, approver, and expires are all mandatory — permanent suppression does not exist (CLI-006).",
///  "type": "object",
///  "required": [
///    "approver",
///    "expires",
///    "finding_id",
///    "justification"
///  ],
///  "properties": {
///    "approver": {
///      "description": "Who approved the suppression.",
///      "type": "string"
///    },
///    "expires": {
///      "description": "Expiry date, RFC 3339 date; after this the Finding gates normally (FR-014).",
///      "type": "string"
///    },
///    "finding_id": {
///      "description": "Finding to suppress (prefix allowed at CLI, full id here).",
///      "$ref": "#/definitions/FindingId"
///    },
///    "justification": {
///      "description": "Why this Finding is suppressed.",
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct SuppressEntry {
    ///Who approved the suppression.
    pub approver: ::std::string::String,
    ///Expiry date, RFC 3339 date; after this the Finding gates normally (FR-014).
    pub expires: ::std::string::String,
    ///Finding to suppress (prefix allowed at CLI, full id here).
    pub finding_id: FindingId,
    ///Why this Finding is suppressed.
    pub justification: ::std::string::String,
}
