//! `cargo xtask gen` — regenerate `multiscan-core` types from `schemas/*.json` (R-4).
//!
//! Pipeline: read schema files in sorted order → merge their `definitions`
//! (duplicate names are an error) → blake3-digest the inputs → run typify with
//! `BTreeMap` as the map type (DET-001) → prettyplease → write
//! `crates/multiscan-core/src/generated.rs` with a DO-NOT-EDIT header and a
//! `SCHEMA_DIGEST` constant. `--check` regenerates and byte-compares instead of
//! writing — the CI drift gate.

use anyhow::{bail, Context, Result};
use typify::{TypeSpace, TypeSpacePatch, TypeSpaceSettings};

use crate::util;

/// Enum-like types that are safe to `Copy` and whose declaration order is
/// semantic: `Severity` and `Confidence` ordinals are load-bearing (spec 2, 8).
const ORDINAL_AND_COPY_TYPES: &[&str] = &[
    "Severity",
    "Confidence",
    "FindingClass",
    "Layer",
    "NetworkImpact",
    "Profile",
    "AssetKind",
    "FindingStatus",
    "Criticality",
    "DataClassification",
];

const OUT_PATH: &str = "crates/multiscan-core/src/generated.rs";

pub fn run(check: bool) -> Result<()> {
    let root = util::workspace_root();
    let schema_files = util::files_with_extension(&root.join("schemas"), "json")?;
    if schema_files.is_empty() {
        bail!("no schema files found under schemas/");
    }

    // Merge all definitions into one namespace; sorted file order + duplicate
    // rejection keep the merge deterministic and unambiguous.
    let mut merged = serde_json::Map::new();
    let mut hasher = blake3::Hasher::new();
    for file in &schema_files {
        let text =
            std::fs::read_to_string(file).with_context(|| format!("reading {}", file.display()))?;
        let name = file
            .file_name()
            .and_then(|n| n.to_str())
            .context("non-UTF-8 schema filename")?;
        hasher.update(name.as_bytes());
        hasher.update(text.as_bytes());

        let doc: serde_json::Value =
            serde_json::from_str(&text).with_context(|| format!("parsing {}", file.display()))?;
        let defs = doc
            .get("definitions")
            .and_then(serde_json::Value::as_object)
            .with_context(|| format!("{name}: expected a top-level \"definitions\" object"))?;
        for (type_name, schema) in defs {
            if merged.insert(type_name.clone(), schema.clone()).is_some() {
                bail!("duplicate definition `{type_name}` (second occurrence in {name})");
            }
        }
    }
    let digest = hasher.finalize().to_hex();

    let root_schema: schemars::schema::RootSchema = serde_json::from_value(serde_json::json!({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "MultiScan",
        "definitions": serde_json::Value::Object(merged),
    }))
    .context("assembling merged root schema")?;

    let mut settings = TypeSpaceSettings::default();
    settings
        // DET-001: additionalProperties maps must never be HashMap.
        .with_map_type("std::collections::BTreeMap")
        .with_derive("PartialEq".to_string());
    for type_name in ORDINAL_AND_COPY_TYPES {
        let mut patch = TypeSpacePatch::default();
        for derive in ["Copy", "Eq", "PartialOrd", "Ord", "Hash"] {
            patch.with_derive(derive);
        }
        settings.with_patch(type_name, &patch);
    }

    let mut type_space = TypeSpace::new(&settings);
    type_space
        .add_root_schema(root_schema)
        .context("typify failed on merged schema")?;

    let file: syn::File =
        syn::parse2(type_space.to_stream()).context("parsing generated tokens")?;
    let body = prettyplease::unparse(&file);

    let generated = format!(
        "// @generated by `cargo xtask gen` from schemas/*.json — DO NOT EDIT (R-4).\n\
         // Edit the schemas and re-run `cargo xtask gen`.\n\
         // schema digest: blake3:{digest}\n\
         #![allow(clippy::all)]\n\n\
         /// blake3 digest of the schema inputs this module was generated from.\n\
         pub const SCHEMA_DIGEST: &str = \"blake3:{digest}\";\n\n\
         {body}"
    );

    let out_path = root.join(OUT_PATH);
    let existing = std::fs::read_to_string(&out_path).unwrap_or_default();
    if check {
        if existing == generated {
            eprintln!("xtask gen --check: OK ({OUT_PATH} is up to date)");
            Ok(())
        } else {
            bail!("{OUT_PATH} is stale — run `cargo xtask gen` and commit the result");
        }
    } else {
        if existing == generated {
            eprintln!("xtask gen: unchanged ({OUT_PATH})");
        } else {
            std::fs::write(&out_path, &generated)
                .with_context(|| format!("writing {}", out_path.display()))?;
            eprintln!("xtask gen: wrote {OUT_PATH} (digest blake3:{digest})");
        }
        Ok(())
    }
}
